<a href="https://colab.research.google.com/github/pySin/AI-Harvard-Course/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor Math Operations

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [4]:
# Addition / sums by tensor index
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
# Subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [9]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [10]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
# Multiplication function
torch.mul(tensor_b, tensor_a)

tensor([ 5, 12, 21, 32])

In [12]:
# Division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [13]:
# Division Function
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [14]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
# Remainder Function
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [16]:
# Exponents / Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [17]:
# Anoher way to add
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])