<a href="https://colab.research.google.com/github/pySin/AI-Harvard-Course/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshpe and View

In [ ]:
reshaped_torch = my_torch.reshape(2, 5)
reshaped_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# Reshape with unknown amount of numbers
reshaped_torch_2 = my_torch.reshape(5, -1)
reshaped_torch_2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [10]:
new_torch = torch.arange(15)
new_torch = new_torch.reshape(-1, 5)
new_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [13]:
# Change torch items
torch_5 = torch.arange(10)
torch_6 = torch_5.reshape(2, -1)
torch_6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
torch_6[0][1] = 555
torch_6

tensor([[  0, 555,   2,   3,   4],
        [  5,   6,   7,   8,   9]])